### ISSUE TITLE
No informatio box or scheme input anywhere after load

### ISSUE THREAD

**Issue by ItzAmirreza** [hallucinate-games/oobabooga-jsonformer-plugin#4]
Hey there, Thank you for this extension.

I tried to use it, however I cannot get it to work. There is no place anywhere for schema placement after the loading of extension. I already did close/reopen my webui, however still not effect, and just jsonformatter is ticked in the session tab.

**Comment by blueskymonster** [comment]
Hey there! Thanks for you interest. We decided to stop maintaining this extension a while ago because many open source models are now available which are trained on giving structured JSON output. It's far more efficient than the way this extension does it which was a gross hack. Try out a model that supports function calling, such as https://huggingface.co/models?sort=trending&search=Function+Calling+Mistral+7B

Good luck out there!
